/* Additional record code for NewtonCooling generated by the OpenModelica Compiler OpenModelica 1.12.0~4-g83bba97. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

